[project]
name = "python-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.5",
    "numpy>=2.1.3",
    "pydantic>=2.9.2",
    "torch>=2.5.1",
    "uvicorn>=0.32.0",
]
